# Generated by Django 4.0.4 on 2022-05-18 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
