# Generated by Django 4.0.4 on 2022-05-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobpost_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='comany_name',
            new_name='company_name',
        ),
    ]
