# Generated by Django 4.0.4 on 2022-05-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_jobpost_pic_jobpost_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('part-time', 'Part-time'), ('full-time', 'full-time')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
