# Generated by Django 4.0.4 on 2022-05-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_application_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
