# Generated by Django 4.0.4 on 2022-05-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('Bod', models.DateField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('resume', models.FileField(upload_to='resume')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobpost')),
            ],
        ),
    ]
