# Generated by Django 4.0.4 on 2022-05-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_jobpost_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobseekers',
            new_name='Application',
        ),
    ]
