# Generated by Django 4.0.4 on 2022-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_name',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
