# Generated by Django 4.0.4 on 2022-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_jobseekers_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='categories',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('customer service', 'Customer service'), ('human resource', 'Human resource'), ('project management', 'Project management'), ('business devlopment', 'Business devlopment'), ('sales & communication', 'Seles & communication'), ('teaching & education', 'Teaching & education'), ('information technology', 'Information technology')], max_length=100),
        ),
    ]
