# Generated by Django 4.0.4 on 2022-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_company_name_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'Hr'), ('admin', 'Admin')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
